version: '3.9'

services:
  postgres:
    container_name: postgres-nest-course
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-course

volumes:
  postgres_data:

networks:
  nest-course:
